refactor: refactor  import strategy to support multiple providers
halo-sigs/plugin-migrate pull request #26
Opened 2023-08-09 09:44 UTC by LIlGG

重构导入策略，支持多 provider

Fixes #2 

```release-note
重构导入策略，支持多 provider
```

2023-08-12 09:15 UTC, ruibaby commented
@LIlGG Ready for review?

2023-08-16 04:07 UTC, LIlGG commented
> @LIlGG Ready for review?

插件功能基本完成，可以开始 review 了。

2023-08-22 06:12 UTC, ruibaby requested changes

2023-08-22 06:12 UTC, ruibaby commented on docs/.vitepress/config.ts
> +          { text: "Rss", link: "/provider/rss" },
```suggestion
          { text: "RSS", link: "/provider/rss" },
```

2023-08-22 06:12 UTC, ruibaby commented on docs/.vitepress/config.ts
> +          { text: "扩展 Provider", link: "/expand/provider" },
是不是应该是 extend ？

2023-08-22 06:12 UTC, ruibaby commented on console/src/index.ts
>  import { definePlugin } from "@halo-dev/console-shared";
不需要修改。

2023-08-22 11:29 UTC, ruibaby reviewed
/lgtm

2023-08-22 11:29 UTC, ruibaby commented
cc @halo-sigs/halo

2023-08-22 15:02 UTC, merged